# SPDX-FileCopyrightText: 2022 sirinsidiator <insidiator@cmos.at>
#
# SPDX-License-Identifier: GPL-3.0-or-later

services:
  eso-profiler-viewer:
    build: .
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - PERFETTO_VERSION=v38.0
    volumes:
      - ./:/files
